package Monitoring::GLPlugin::SNMP::MibsAndOids::ACFAULTTC;

$Monitoring::GLPlugin::SNMP::MibsAndOids::origin->{'AC-FAULT-TC'} = {
  url => '',
  name => 'AC-FAULT-TC',
};

#$Monitoring::GLPlugin::SNMP::MibsAndOids::mib_ids->{'AC-FAULT-TC'} =

$Monitoring::GLPlugin::SNMP::MibsAndOids::mibs_and_oids->{'AC-FAULT-TC'} = {
};

$Monitoring::GLPlugin::SNMP::MibsAndOids::definitions->{'AC-FAULT-TC'} = {
  'AcAlarmEventType' => {
    '0' => 'other',
    '1' => 'communicationsAlarm',
    '2' => 'qualityOfServiceAlarm',
    '3' => 'processingErrorAlarm',
    '4' => 'equipmentAlarm',
    '5' => 'environmentalAlarm',
  },
  'AcAlarmProbableCause' => {
    '0' => 'other',
    '1' => 'adapterError',
    '2' => 'applicationSubsystemFailure',
    '3' => 'bandwidthReduced',
    '4' => 'callEstablishmentError',
    '5' => 'communicationsProtocolError',
    '6' => 'communicationsSubsystemFailure',
    '7' => 'configurationOrCustomizationError',
    '8' => 'congestion',
    '9' => 'corruptData',
    '10' => 'cpuCyclesLimitExceeded',
    '11' => 'dataSetOrModemError',
    '12' => 'degradedSignal',
    '13' => 'dteDceInterfaceError',
    '14' => 'enclosureDoorOpen',
    '15' => 'equipmentMalfunction',
    '16' => 'excessiveVibration',
    '17' => 'fileError',
    '18' => 'fireDetected',
    '19' => 'floodDetected',
    '20' => 'framingError',
    '21' => 'heatingVentCoolingSystemProblem',
    '22' => 'humidityUnacceptable',
    '23' => 'inputOutputDeviceError',
    '24' => 'inputDeviceError',
    '25' => 'lanError',
    '26' => 'leakDetected',
    '27' => 'localNodeTransmissionError',
    '28' => 'lossOfFrame',
    '29' => 'lossOfSignal',
    '30' => 'materialSupplyExhausted',
    '31' => 'multiplexerProblem',
    '32' => 'outOfMemory',
    '33' => 'ouputDeviceError',
    '34' => 'performanceDegraded',
    '35' => 'powerProblem',
    '36' => 'pressureUnacceptable',
    '37' => 'processorProblem',
    '38' => 'pumpFailure',
    '39' => 'queueSizeExceeded',
    '40' => 'receiveFailure',
    '41' => 'receiverFailure',
    '42' => 'remoteNodeTransmissionError',
    '43' => 'resourceAtOrNearingCapacity',
    '44' => 'responseTimeExecessive',
    '45' => 'retransmissionRateExcessive',
    '46' => 'softwareError',
    '47' => 'softwareProgramAbnormallyTerminated',
    '48' => 'softwareProgramError',
    '49' => 'storageCapacityProblem',
    '50' => 'temperatureUnacceptable',
    '51' => 'thresholdCrossed',
    '52' => 'timingProblem',
    '53' => 'toxicLeakDetected',
    '54' => 'transmitFailure',
    '55' => 'transmitterFailure',
    '56' => 'underlyingResourceUnavailable',
    '57' => 'versionMismatch',
    '58' => 'authenticationFailure',
    '59' => 'breachOfConfidentiality',
    '60' => 'cableTamper',
    '61' => 'delayedInformation',
    '62' => 'denialOfService',
    '63' => 'duplicateInformation',
    '64' => 'informationMissing',
    '65' => 'informationModificationDetected',
    '66' => 'informationOutOfSequence',
    '67' => 'intrusionDetection',
    '68' => 'keyExpired',
    '69' => 'nonRepudiationFailure',
    '70' => 'outOfHoursActivity',
    '71' => 'outOfService',
    '72' => 'proceduralError',
    '73' => 'unauthorizedAccessAttempt',
    '74' => 'unexpectedInformation',
  },
  'AcAlarmSeverity' => {
    '0' => 'cleared',
    '1' => 'indeterminate',
    '2' => 'warning',
    '3' => 'minor',
    '4' => 'major',
    '5' => 'critical',
  },
};
